language: java
sudo: false
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "ulisse1996"
script:
  - mvn -T8 clean install jacoco:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'
after_success:
  - bash <(curl -s https://codecov.io/bash)
dist: trusty