CREATE TABLE TABLE1INSERT (
    COL1 VARCHAR(5),
    COL2 NUMERIC(10)
);

CREATE TABLE TABLE2INSERT (
    COL1 DATE
);

CREATE TABLE TABLE3INSERT (
    COL1 DATE
);

CREATE TABLE TABLE4INSERT (
    COL1 VARCHAR(5),
    COL2 NUMERIC(10)
);