
CREATE TABLE TAB1 (
    COL1 NUMERIC(10),
    COL2 NUMERIC(4),
    COL3 VARCHAR(5)
);

CREATE TABLE TAB2 (
    COL4 NUMERIC(10),
    COL5 NUMERIC(4,3),
    COL6 VARCHAR(5)
);

CREATE TABLE TAB3 (
    COL1 NUMERIC(4,1),
    COL2 TIMESTAMP,
    COL3 DATE,
    COL4 CHAR
);

CREATE TABLE TAB_TYPE (
    COL1 TIME,
    COL2 LONGVARBINARY,
    COL3 BOOLEAN
);

INSERT INTO TAB1 (COL1, COL2, COL3) VALUES (2,3,'TEST');
INSERT INTO TAB1 (COL1, COL2, COL3) VALUES (3,4,'TEST2');


INSERT INTO TAB2 (COL4, COL5, COL6) VALUES (2,3,'TEST');
INSERT INTO TAB2 (COL4, COL5, COL6) VALUES (2.5, 3, 'TEST');

INSERT INTO TAB3 (COL1, COL2, COL3, COL4) VALUES (2.5, CURRENT_TIMESTAMP, CURRENT_DATE, 'C');

INSERT INTO TAB_TYPE (COL1, COL2, COL3) VALUES (CURRENT_TIME, X'FFD8FFE000104A4640', TRUE);
