CREATE TABLE TABLE1 (
    COL1 VARCHAR(25),
    COL2 NUMERIC(15)
);

INSERT INTO TABLE1 (COL1, COL2) VALUES ('PRE_UPDATE',15);
INSERT INTO TABLE1 (COL1, COL2) VALUES ('PRE_UPDATE',16);

CREATE TABLE TABLE2 (
    COL1 VARCHAR(25),
    COL2 NUMERIC(15)
);

INSERT INTO TABLE2 (COL1, COL2) VALUES ('DATE', 15);
INSERT INTO TABLE2 (COL1, COL2) VALUES ('DATE', 25);

CREATE TABLE TABLE3 (
    COL1 VARCHAR(25),
    COL2 NUMERIC(15)
);


INSERT INTO TABLE3 (COL1, COL2) VALUES ('DATE', 15);
INSERT INTO TABLE3 (COL1, COL2) VALUES ('DATE', 25);

CREATE TABLE TABLE4 (
    COL1 VARCHAR(25),
    COL2 NUMERIC(15)
);

CREATE TABLE TABLE_DUAL (
    COL1 VARCHAR(25)
);

INSERT INTO TABLE_DUAL (COL1) VALUES ('FROM_DUAL');

INSERT INTO TABLE4 (COL1, COL2) VALUES ('DATE', 15);
